set unstable

config_home := "$HOME/.config/nushell"
dir := if os() == "macos" {"mac"} else {"linux"}
pwd := absolute_path(".")

# Display this help
default:
    @just --list

# Configure nushell
setup:
    mkdir -p {{config_home}}
    ln -sf {{pwd}}/{{dir}}/config.nu "$HOME/.config/nushell/config.nu"
    ln -sf {{pwd}}/{{dir}}/env.nu "$HOME/.config/nushell/env.nu"
    ln -sf {{pwd}}/{{dir}}/login.nu "$HOME/.config/nushell/login.nu"


# Install nushell
[linux]
install:
    cargo install --locked nu

# Install nushell
[macos]
install:
    brew install nushell
