set unstable

config_home := "$HOME/.config/zellij"
pwd := absolute_path(".")
invocation_dir := invocation_directory()

# Display this help
default:
  @just --list --unsorted

# Start or switch zellij sessions (nushell version)
[no-cd]
sessionizer:
  nu {{pwd}}/scripts/sessionizer.nu

# Start or switch zellij sessions (zsh version)
[no-cd]
sessionizer-zsh:
  zsh {{pwd}}/scripts/sessionizer.zsh

# Configure zellij
setup: configure-symlinks

install: install-plugins
    cargo install --locked zellij

configure-symlinks:
    # ln -sf {{pwd}}/scripts/sessionizer-david.zsh

# Install plugins
[script("zsh")]
install-plugins:
  if [ ! -f ./plugins/vim-zellij-navigator.wasm ]; then
    wget -P ./plugins https://github.com/hiasr/vim-zellij-navigator/releases/download/0.3.0/vim-zellij-navigator.wasm
  else
    echo "vim-zellij-navigator plugin is already installed"
  fi
  if [ ! -f ./plugins/zellij-switch.wasm ]; then
    wget -P ./plugins https://github.com/mostafaqanbaryan/zellij-switch/releases/download/0.2.1/zellij-switch.wasm
  else
    echo "zellij-switch plugin is already installed"
  fi
