set unstable

zsh_home := "$HOME/.config/zsh"
pwd := absolute_path(".")
dir := if os() == "macos" {"mac"} else {"linux"}

# Display this help
default:
  @just --list --unsorted

# Configure zsh
setup: create-symlinks install

# Install oh-my-zsh and plugins
install:
    [ -d "$HOME/.zplug" ] || git clone https://github.com/zplug/zplug $HOME/.zplug

# Configure ZSH
create-symlinks:
   mkdir -p {{zsh_home}}
   mkdir -p "$HOME/scripts"
   mkdir -p "$HOME/.config/atuin"
   ln -sf {{pwd}}/atuin.toml "$HOME/.config/atuin/config.toml"
   ln -sf {{pwd}}/{{dir}}/main.zsh "$HOME/.zshrc"
   ln -sf {{pwd}}/{{dir}}/01-env.zsh "$HOME/.config/zsh/01-env.zsh"
   # ln -sf {{pwd}}/{{dir}}/0-aliases.zsh "$HOME/.config/zsh/02-aliases.zsh"
   ln -sf {{pwd}}/common/02-aliases.zsh "$HOME/.config/zsh/02-aliases.zsh"
   ln -sf {{pwd}}/common/03-functions.zsh "$HOME/.config/zsh/03-functions.zsh"
   ln -sf {{pwd}}/common/04-integrations.zsh "$HOME/.config/zsh/04-integrations.zsh"
   ln -sf {{pwd}}/common/05-options.zsh "$HOME/.config/zsh/05-options.zsh"
   ln -sf {{pwd}}/common/06-plugins.zsh "$HOME/.config/zsh/06-plugins.zsh"

